### ISSUE TITLE
Missing header file.

### ISSUE THREAD

**Issue by jfjlaros** [jfjlaros/simpleRPC#17]
On this line, a non-existing header seems to be included.

https://github.com/jfjlaros/simpleRPC/blob/e586d1d391db59b770a1344c89f90b2a82427398/examples/wifi101/wifi101.ino#L2

**Comment by chrisflesher** [comment]
This is an external dependency:
```
arduino-cli lib install WiFi101
```

Maybe include a comment here?

**Comment by jfjlaros** [comment]
I see, thanks.
