### ISSUE TITLE
Allow class functions

### ISSUE THREAD

**Issue by chrisflesher** [jfjlaros/simpleRPC#19]
It would make things a bit more convenient if it were possible to use class functions with the template system:

```
Adafruit_BME280 bme;

void setup(void)
{
  Serial.begin(9600);
  bme.begin();
}

void loop(void)
{
  interface(
    Serial,
    bme.readTemperature, F("get_temperature: @return: Temperature [C]"));
}
```

I'm not sure how difficult / if it is worth doing this with the current template system? It is not too much trouble to just wrap these in another function.

**Comment by jfjlaros** [comment]
This is already [possible](https://simplerpc.readthedocs.io/en/latest/usage.html#exporting-class-methods). The following line should work:

    pack(&bme, &Adafruit_BME280::readTemperature), F("get_temperature: @return: Temperature [C]")

**Comment by chrisflesher** [comment]
Nice! Thanks.

**Comment by slaff** [comment]
And what is solution when this method is overloaded ? For example if `Adafruit_BME280::readTemperature` has the following:
```C++
void Adafruit_BME280::readTemperature(uint8_t& degrees);
uint8_t Adafruit_BME280::readTemperature(); 
```

**Comment by jfjlaros** [comment]
To select the first option, something like this should work:

```cpp
(void(Adafruit_BME280::*)(uint8_t&))&Adafruit_BME280::readTemperature
```

**Comment by slaff** [comment]
Awesome! Thank you @jfjlaros
