### ISSUE TITLE
Pack not existing

### ISSUE THREAD

**Issue by suahelen** [jfjlaros/simpleRPC#38]
the method `pack` does not exist anymore. It was removed in https://github.com/jfjlaros/simpleRPC/commit/4710992a262ddef08a788e27e85c235958dc8ac9

and exchanged with `makeTuple`.

work ok its just not up to date in the docs. 
Or rather the description of how to use methods of objects was not updated.

**Comment by jfjlaros** [comment]
Duplicate of #35.
