### ISSUE TITLE
Support for SAMD architecture

### ISSUE THREAD

**Issue by chrisflesher** [jfjlaros/simpleRPC#8]
I'm using a feather M0 and would like to use this library for SAMD architecture but when I try to compile it's saying the library is only for AVR micro-controllers.

I'm imagining a `SerialIO` class would replace `HardwareSerialIO` and `SoftwareSerialIO`, like this:
```
#ifndef SIMPLE_RPC_SERIAL_IO_H_
#define SIMPLE_RPC_SERIAL_IO_H_

#include <Arduino.h>

class SerialIO {
  public:
    SerialIO(void) {}
    void begin(Stream&);
    size_t available(void);
    size_t read(byte*, size_t);
    size_t write(byte*, size_t);
  private:
    Stream* _ss;
};

typedef SerialIO HardwareSerialIO;  // for backwards compatibility
typedef SerialIO SoftwareSerialIO;  // for backwards compatibility

#endif
```

**Comment by chrisflesher** [comment]
I tried making this change and performed the following steps:
- uploaded the demo program to an M0
- installed the python client using pip
- ran `simple_rpc list` in a terminal

Now am getting the following error: `simple_rpc: error: top level type can not be tuple`

**Comment by jfjlaros** [comment]
Perhaps a separate plugin and guards around the serial plugin includes in `simpleRPC.h` would be a better approach.

**Comment by chrisflesher** [comment]
That would work also! I tried reducing the demo program to the following and it worked!
```
#include <simpleRPC.h>

HardwareSerialIO io;

int inc(int a) {
  return a + 1;
}

void setup(void) {
  Serial.begin(9600);
  io.begin(Serial);
}

void loop(void) {
  interface(
    io,
    inc, F("inc: Increment a value. @a: Value. @return: a + 1.")
  );
}
```

**Comment by chrisflesher** [comment]
I think HardwareSerial and SoftwareSerial inherit from Stream?

**Comment by jfjlaros** [comment]
I am not sure about this tuple error. It does not occur when using the HardwareSerial plugin.

**Comment by jfjlaros** [comment]
The philosophy behind these plugins is to only pass a pointer to a communication interface. This way, the plugin does not need to know about any of the configuration possibilities that the interface may have. Making a more generic interface for both hardware and software serial interfaces would mean more maintenance, that is why I would prefer a separate thin wrapper.

**Comment by chrisflesher** [comment]
Sounds good.

**Comment by jfjlaros** [comment]
I am open for pull requests, if you have something working.

**Comment by chrisflesher** [comment]
I can't push to this repo? Do I need to fork it and then push to that?

**Comment by chrisflesher** [comment]
Ok, I think I figured it out...

**Comment by chrisflesher** [comment]
I submitted a PR, I tried to use #defines as suggested but found Arduino was still trying to compile the `HardwareSerial` and `SoftwareSerial` `io.cpp` files even though the header files were not being used. I could add #defines to those files also but seemed simpler to inherit. I know this isn't what you wanted but maybe will still work? Do you have an AVR you're able to test this with easily to see if you can still configure `SoftwareSerial` or `HardwareSerial` like you want?

It seems like the other error I was getting about tuples was because I was using python 2.7 instead of python 3.

**Comment by chrisflesher** [comment]
This library is really awesome btw!!

**Comment by jfjlaros** [comment]
Thank you. I will perform some tests tomorrow.

**Comment by jfjlaros** [comment]
Everything seems to check out fine. I just merged your changes.

**Comment by chrisflesher** [comment]
Cool, thanks!

**Comment by jfjlaros** [comment]
I see that both `EthernetClient` as well als `TwoWire` ultimately inherit from `Stream`. Perhaps this fix makes all the plugins redundant.
